stages:
  - fetch_repos

variables:
  GITLAB_ACCESS_TOKEN: $ACCESS_TOKEN  # Ensure this is defined in your GitLab CI/CD settings
  GITLAB_GROUP_ID: "your_group_id"    # Ensure this is set to your target GitLab group ID

fetch_repo_details:
  stage: fetch_repos
  image: alpine:latest  # Alpine is lightweight and includes essential tools
  before_script:
    - apk update && apk add jq curl  # Install jq and curl if not present
  script:
    - |
      BASE_URL="https://sfgitlab.opr.statefarm.org/api/v4"
      PAGE=1
      PER_PAGE=100
      echo "[]" > all_projects.json  # Initialize a JSON file to store project details

      # Loop through all available pages of projects
      while :; do
        # Fetch project data from GitLab API
        PROJECTS_JSON=$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_ACCESS_TOKEN}" "${BASE_URL}/groups/${GITLAB_GROUP_ID}/projects?include_subgroups=true&per_page=${PER_PAGE}&page=${PAGE}")

        # If no projects are returned, exit the loop
        if [ -z "$(echo $PROJECTS_JSON | jq '.[]')" ]; then
          break
        fi
        
        # Process each project to fetch and analyze branch data
        echo "$PROJECTS_JSON" | jq -c '.[]' | while read project; do
          PROJECT_ID=$(echo $project | jq -r '.id')
          PROJECT_NAME=$(echo $project | jq -r '.name' | sed 's/\"/\\\"/g')
          
          # Fetch branch data for the current project
          BRANCHES_JSON=$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_ACCESS_TOKEN}" "${BASE_URL}/projects/${PROJECT_ID}/repository/branches")

          # Process each branch to check if it is protected
          echo "$BRANCHES_JSON" | jq -c '.[]' | while read branch; do
            BRANCH_NAME=$(echo $branch | jq -r '.name' | sed 's/\"/\\\"/g')
            IS_PROTECTED=$(echo $branch | jq -r '.protected')
            
            # Save details of protected branches
            if [[ "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "main" ]] && [[ "$IS_PROTECTED" == "true" ]]; then
              echo "{\"project_name\": \"$PROJECT_NAME\", \"branch_name\": \"$BRANCH_NAME\", \"protected\": $IS_PROTECTED}" >> all_projects.json
            fi
          done
        done

        # Increment the page number to fetch the next page
        ((PAGE++))
      done
  artifacts:
    paths:
      - all_projects.json  # Preserve the JSON file as a build artifact
    expire_in: 1 week
  only:
    - master  # Adjust to your branch strategy as needed
