stages:
  - fetch_repos

fetch_repo_details:
  stage: fetch_repos
  image: python:3.9  # Ensure Python is available
  before_script:
    - pip install urllib3  # Although urllib is part of the standard library, urllib3 might be used for enhanced features
  script:
    - python fetch_repos.py
  variables:
    GITLAB_ACCESS_TOKEN: $ACCESS_TOKEN  # Define this in GitLab's CI/CD settings
    GITLAB_GROUP_PATH: "Turing"          # Adjust according to your specific group path
  only:
    - master
