fetch_repo_details:
  stage: fetch_repos
  image: python:3.9  # Using a Python image
  before_script:
    - pip install requests  # Install necessary Python package
  script:
    - python fetch_repos.py  # Run your Python script
  artifacts:
    paths:
      - repo_details.txt
    expire_in: 1 week
  only:
    - master
