stages:
  - fetch_repos

variables:
  GITLAB_ACCESS_TOKEN: $ACCESS_TOKEN  # Set in CI/CD settings
  GITLAB_GROUP_ID: "your_group_id"    # Set in CI/CD settings

fetch_repo_details:
  stage: fetch_repos
  image: alpine:latest  # Using Alpine for its lightweight nature
  before_script:
    - apk update && apk add jq curl  # Ensure jq and curl are installed
  script:
    - |
      BASE_URL="https://sfgitlab.opr.statefarm.org/api/v4"
      PAGE=1
      PER_PAGE=100
      echo "[]" > all_projects.json

      while :; do
        # Fetch projects from the current page
        PROJECTS_JSON=$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_ACCESS_TOKEN}" "${BASE_URL}/groups/${GITLAB_GROUP_ID}/projects?include_subgroups=true&per_page=${PER_PAGE}&page=${PAGE}")
        
        # If no projects are returned, break the loop
        if [ -z "$(echo $PROJECTS_JSON | jq '.[]')" ]; then
          break
        fi
        
        # Process each project incrementally
        echo "$PROJECTS_JSON" | jq -c '.[]' | while read i; do
          PROJECT_ID=$(echo $i | jq -r '.id')
          PROJECT_NAME=$(echo $i | jq -r '.name' | sed 's/\"/\\\"/g')
          
          # Fetch branches of the project and process each branch
          BRANCHES_JSON=$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_ACCESS_TOKEN}" "${BASE_URL}/projects/${PROJECT_ID}/repository/branches")
          echo "$BRANCHES_JSON" | jq -c '.[]' | while read j; do
            BRANCH_NAME=$(echo $j | jq -r '.name' | sed 's/\"/\\\"/g')
            IS_PROTECTED=$(echo $j | jq -r '.protected')
            
            # Construct JSON entry for each branch
            if [[ "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "main" ]]; then
              NEW_ENTRY="{\"project_name\": \"$PROJECT_NAME\", \"branch_name\": \"$BRANCH_NAME\", \"protected\": $IS_PROTECTED}"
              echo $(cat all_projects.json | jq ". + [$NEW_ENTRY]") > all_projects.json
            fi
          done
        done

        # Increment the page number to fetch the next page
        ((PAGE++))
      done
  artifacts:
    paths:
      - all_projects.json  # Save all projects data as an artifact
    expire_in: 1 week
  only:
    - master  # Specify the branch
